name: firebase_auth_youtube
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  cupertino_icons: ^1.0.6
  
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
